name: Lint and Format

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lint-and-format:
    name: Lint and Format Check
    runs-on: ubuntu-latest

    steps:
      # Шаг 1. Клонирование репозитория
      - name: Checkout repository
        uses: actions/checkout@v4

      # Шаг 2. Установка clang-format
      - name: Install clang-format
        run: sudo apt-get install -y clang-format

      # Шаг 3. Проверка форматирования
      - name: Check code formatting with clang-format
        run: |
          # Проверка форматирования
          clang-format --dry-run --Werror -style=file source/**/*.cpp source/**/*.h

      # Шаг 4. Установка cppcheck (линтер для C++)
      - name: Install cppcheck
        run: sudo apt-get install -y cppcheck

      # Шаг 5. Линтинг кода
      - name: Run linting with cppcheck
        run: |
          cppcheck --enable=all --inconclusive --std=c++17 --error-exitcode=1 source/